import { Glob } from 'bun';
import { parseNote, type ParsedNote } from './lib/note-parser.ts';
import { readFile, writeFile } from 'node:fs/promises';

const ROOT = '/Users/user/aladdin/obsidian/Codebase';
const MAX_DEPTH = 6;

function buildChain(fqn: string, notes: Map<string, ParsedNote>, depth: number, visited: Set<string>): string[] {
    const lines: string[] = [];
    const prefix = '  '.repeat(depth);
    const indicator = depth === 0 ? '' : '↳ ';

    if (depth > MAX_DEPTH) {
        lines.push(`${prefix}${indicator}... (max depth ${MAX_DEPTH} reached)`);
        return lines;
    }
    if (visited.has(fqn)) {
        lines.push(`${prefix}${indicator}[[${fqn}]] (cycle, already shown)`);
        return lines;
    }

    const note = notes.get(fqn);
    if (!note) {
        lines.push(`${prefix}${indicator}[[${fqn}]] (out of scope)`);
        return lines;
    }

    lines.push(`${prefix}${indicator}[[${fqn}]]`);
    const newVisited = new Set(visited).add(fqn);
    const downstream = [
        ...note.calls.managerMethods,
        ...note.calls.rpcCrossServer,
        ...note.calls.otherManagers,
    ];

    for (const d of downstream) {
        lines.push(...buildChain(d, notes, depth + 1, newVisited));
    }
    return lines;
}

function updateAutoGeneratedBlock(raw: string, newContent: string): string | null {
    const re = /<!-- AUTO-GENERATED, DO NOT EDIT -->([\s\S]*?)<!-- END AUTO-GENERATED -->/;
    if (!re.test(raw)) return null;
    return raw.replace(re, `<!-- AUTO-GENERATED, DO NOT EDIT -->\n${newContent}\n<!-- END AUTO-GENERATED -->`);
}

async function main() {
    const glob = new Glob('**/*.md');
    const notes = new Map<string, ParsedNote>();
    for await (const rel of glob.scan(ROOT)) {
        const note = await parseNote(`${ROOT}/${rel}`);
        if (note) notes.set(note.fqn, note);
    }
    console.log(`Loaded ${notes.size} notes`);

    let modified = 0;
    for (const note of notes.values()) {
        if (note.type !== 'rpc-method' && note.type !== 'manager-method') continue;
        const chain = buildChain(note.fqn, notes, 0, new Set()).join('\n');
        const content = chain || '（無下游呼叫）';
        const raw = await readFile(note.path, 'utf-8');
        const updated = updateAutoGeneratedBlock(raw, content);
        if (updated && updated !== raw) {
            await writeFile(note.path, updated);
            modified++;
        }
    }
    console.log(`Generated call chains for ${modified} methods`);
}

await main();
